services:
  gateway:
    build:
      context: ./src/Gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    networks:
      - evaluation-network

  sales-api:
    build:
      context: ./src
      dockerfile: SalesApi/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - evaluation-network

networks:
  evaluation-network:
    driver: bridge
