version: "3.9"

services:
  gateway:
    build:
      context: ./src/Gateway
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - evaluation-network

  sales-api:
    build:
      context: ./src/SalesApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - evaluation-network

networks:
  evaluation-network:
    driver: bridge
